### ISSUE TITLE
Feedback del ejercicio de evaluación intermedia del sprint 2

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcar-s2-evaluacion-intermedia-ashesnei#1]
HTML medio espartano pero muy suficiente para trabajar, un poco de indentación no le haría daño. El js CASI funciona, te ha faltado muy poco y no genera error que siempre mola :) Te voy a proponer unos ajustes para que funcione y te doy un guión por si te ayuda pero sola ibas por buen camino, así que con guión o sin guión te animo a que lo termines.

## Ajustes necesarios para que el invento funcione
- [x] Cuando recogemos valores de DOM siempre son cadenas así que un `parseInt` nos va a salvar el día
- [x] Revisa cómo aplicamos un `addEventListener`, quizás hay paréntesis de más ;)

![:)](https://media.giphy.com/media/Mp4hQy51LjY6A/giphy.gif)

En tu caso me parece que vas por buen camino pero te dejo el guión, porsiaca:

```
// Guardar la referencia a todos los elementos del DOM que vamos a usar en variables

// Generar el número aleatorio
// Y guardarlo en una variable

// Inicializar a 0 una variable de contador

// Crear una función que se ejecute cuando haga click en el botón de prueba
//  Esta función tiene que hacer:
//  1 - incrementar el contador
//  2 - y pintar el contador en mi html

//  3 - recoger el valor del campo
//  4 - Compararlo con mi número aleatorio
//    - Si son iguales -> pintar el mensaje de "Ganadora"
//    - Si es menor -> pintar el mensaje de "te has quedado corta"
//    - Si es mayor -> pintar el mensaje de "te has pasado"

// Asignar un listener al botón de prueba para que ejecute una función al hacer click
```
![Al turrón](https://media.giphy.com/media/q5qGxbZh4UiaI/giphy.gif)

**Comment by ashesnei** [comment]
Vale, lo tengo feo pero efectivo y muahahahaha.. un poco gamberro. (Contexto clase, esto no se hace en un ambiente laboral real, etc.. i know, pero es mas diver!)

**Comment by oneeyedman** [comment]
Muy buen trabajo. Te voy a poner unas issues de "para dejarlo fetén", sin prisa ahí las tienes
