### ISSUE TITLE
La carpeta node_modules no debe estar en el repo

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcar-s2-evaluacion-intermedia-ashesnei#2]
Esta carpeta no debería subirse nunca y para ello la listamos en el archivo `.gitignore` (puedes ver un ejemplo en la línea 42 del .gitignore del kit de Adalab: https://github.com/Adalab/Adalab-web-starter-kit/blob/master/.gitignore)

Tu misión, si decides aceptarla es eliminar esta carpeta del repo. Para ello puedes seguir estos sencillos pasos: 

1. borrar la carpeta, add, commit y push.
1. Añadir un archivo .gitignore propio con "node_modules" o incluir el del kit de Adalab, add, commit y push.
1. volver a hacer un `npm install` en tu local y ver que, efectivamente, esa carpeta está ya ignorada

Al turrón?

![MI](https://media.giphy.com/media/5JJ7fiwhy0VgY/giphy.gif)

**Comment by ashesnei** [comment]
Hecho! (casi me cargo el ordenador al hacer npm install)
