### ISSUE TITLE
JS enlazado

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/dorcar-s2-evaluacion-intermedia-ashesnei#3]
Es un detallico pero el archivo correcto que vamos a enlazar es `main.min.js` que es el que general el kit cada vez que guardamos main.js ;)

![Yay](https://media.giphy.com/media/OjWso03jVjGJq/giphy.gif)

**Comment by ashesnei** [comment]
Hecho!
![Molando fuerte](https://media.giphy.com/media/nNxT5qXR02FOM/giphy.gif)
